#!/bin/bash

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"


if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Run as ${RED}root${NC}"
    exit 1
fi

chmod +x * >/dev/null 2>&1

mv onionbox-nft onionbox osh oshnft /usr/bin >/dev/null && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} Now you can try ${YELLOW}'onionbox start'${GREEN} or, ${YELLOW}'onionbox-nft start'${GREEN} if you prefer an nftables firewall${BLUE}(${GREEN}done${BLUE})${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Stop changing the name of the script, you will have to move it manually${NC}" | exit 1

