#!/bin/bash

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"


if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN}Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

chmod +x * >/dev/null 2>&1

mv archnon-nft archnon /usr/bin >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Files are part of your path, try: ${YELLOW}'archnon start/archnon-nft start'${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Stop changing the name of the script, you will have to move it manually${NC}"

